apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-a-objects
  namespace: team-a
  labels:
    app.kubernetes.io/name: team-a-objects
    app.kubernetes.io/part-of: quota-guardrails
spec:
  hard:
    services.loadbalancers: "0"
    services.nodeports: "0"
    persistentvolumeclaims: "4"
    requests.storage: 20Gi
    configmaps: "20"
    secrets: "20"
